compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
gpu_ids: 0,1,2
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 3
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
